{
  "language": "c",
  "sudo": "required",
  "dist": "trusty",
  "before_install": [
    "sudo apt-get update",
    "sudo apt-get -y install libnetcdf-dev build-essential libnetcdff5 libnetcdfc7 libnetcdfc++4 libcf0 netcdf-doc netcdf-bin openjdk-6-jre-headless",
    "sudo apt-get -y install libgd-dev libgd2-xpm-dev debhelper",
    "chmod 755 ./install-icc.sh",
    "sudo ./install-icc.sh --components icc,openmp,ipp,ifort --dest /opt/intel"
  ],
  "script": [
    "source /opt/intel/bin/compilervars.sh intel64",
    "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/ism/bin/intel64",
    "git clone --depth=50 --branch=master https://github.com/AquaticEcoDynamics/libutil.git AquaticEcoDynamics/libutil",
    "./build_glm.sh",
    "./glm-aed/src/glm --help"
  ],
  "after_success": null,
  "group": "stable",
  "os": "linux"
}
